package it.unipi;

import javax.swing.*;

public class Board extends JFrame{
    private JPanel contentPane; // Generated by the form designer
    private JLabel paneTitle; // Generated by the form designer

    public Board() {
        setTitle("Matching Pairs");
        setSize(600, 400);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        // Set contentPane as the main panel of the JFrame
        setContentPane(contentPane);
        paneTitle.setText("Card Board");

    }
}
